# Generated by Django 5.2.2 on 2025-07-01 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcollaborator',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationassignment',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_assignments', to='books.chapter'),
        ),
        migrations.AddField(
            model_name='translationassignment',
            name='target_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.language'),
        ),
        migrations.AddField(
            model_name='translationassignment',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookcollaborator',
            unique_together={('book', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='translationassignment',
            unique_together={('chapter', 'translator', 'target_language')},
        ),
    ]
