# Generated by Django 5.2.2 on 2025-07-01 19:50

import accounts.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to=accounts.models.User.user_avatar_path
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.User.user_avatar_thumbnail_path,
            ),
        ),
    ]
