# Generated by Django 5.2.2 on 2025-07-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar_alter_user_avatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcollaborator',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('co_author', 'Co-Author'), ('translator', 'Translator'), ('reviewer', 'Reviewer'), ('editor', 'Editor')], max_length=20),
        ),
    ]
