# Generated by Django 5.2.2 on 2025-07-18 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key_configured', models.BooleanField(default=False)),
                ('default_model', models.CharField(max_length=100)),
                ('available_models', models.JSONField(default=list)),
                ('cost_per_1k_tokens', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMQualityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('translation', 'Translation'), ('abstract_generation', 'Abstract Generation'), ('key_terms_extraction', 'Key Terms Extraction'), ('chapter_division', 'Chapter Division'), ('other', 'Other')], max_length=50)),
                ('total_calls', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('avg_quality_score', models.FloatField(default=0.0)),
                ('total_tokens_used', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('source_language', models.CharField(blank=True, max_length=10)),
                ('target_language', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_integration.llmprovider')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('provider', 'model_name', 'operation', 'period_start', 'source_language', 'target_language')},
            },
        ),
        migrations.CreateModel(
            name='LLMServiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('translation', 'Translation'), ('abstract_generation', 'Abstract Generation'), ('key_terms_extraction', 'Key Terms Extraction'), ('chapter_division', 'Chapter Division'), ('other', 'Other')], max_length=50)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited')], max_length=20)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('source_language', models.CharField(blank=True, max_length=10)),
                ('target_language', models.CharField(blank=True, max_length=10)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_integration.llmprovider')),
                ('source_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls_as_source', to='books.book')),
                ('source_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls_as_source', to='books.chapter')),
                ('target_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls_as_target', to='books.book')),
                ('target_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls_as_target', to='books.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'operation', 'status'], name='llm_integra_provide_b5e63b_idx'), models.Index(fields=['created_at'], name='llm_integra_created_a46c86_idx'), models.Index(fields=['source_book', 'source_chapter'], name='llm_integra_source__62b091_idx'), models.Index(fields=['target_book', 'target_chapter'], name='llm_integra_target__1f6251_idx')],
            },
        ),
    ]
