# Generated by Django 5.2.2 on 2025-06-29 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("llm_integration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="llmservicecall",
            name="llm_integra_book_id_6d3f57_idx",
        ),
        migrations.RemoveField(
            model_name="llmservicecall",
            name="book",
        ),
        migrations.RemoveField(
            model_name="llmservicecall",
            name="chapter",
        ),
        migrations.AddField(
            model_name="llmservicecall",
            name="source_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_calls_as_source",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="llmservicecall",
            name="source_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_calls_as_source",
                to="books.chapter",
            ),
        ),
        migrations.AddField(
            model_name="llmservicecall",
            name="target_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_calls_as_target",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="llmservicecall",
            name="target_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_calls_as_target",
                to="books.chapter",
            ),
        ),
        migrations.AddIndex(
            model_name="llmservicecall",
            index=models.Index(
                fields=["source_book", "source_chapter"],
                name="llm_integra_source__62b091_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmservicecall",
            index=models.Index(
                fields=["target_book", "target_chapter"],
                name="llm_integra_target__1f6251_idx",
            ),
        ),
    ]
