# Generated by Django 5.2.2 on 2025-07-07 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('co_author', 'Co-Author'), ('translator', 'Translator'), ('reviewer', 'Reviewer'), ('editor', 'Editor')], max_length=20)),
                ('permissions', models.JSONField(default=dict, help_text='Granular permissions for this collaboration')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Collaborator',
                'verbose_name_plural': 'Book Collaborators',
                'unique_together': {('book', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TranslationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_translations', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_assignments', to='books.chapter')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.language')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation Assignment',
                'verbose_name_plural': 'Translation Assignments',
                'unique_together': {('chapter', 'translator', 'target_language')},
            },
        ),
    ]
