# Generated by Django 5.2.2 on 2025-06-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="target_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="languages.language",
            ),
        ),
    ]
