# Generated by Django 5.2.2 on 2025-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0002_alter_translation_target_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
