# Generated by Django 5.2.2 on 2025-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0003_translation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="key_terms",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
