# Generated by Django 5.2.2 on 2025-07-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content_file_path',
            field=models.CharField(blank=True, help_text='Path to JSON content file', max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='paragraph_style',
            field=models.CharField(choices=[('single_newline', 'Single Newline'), ('double_newline', 'Double Newline'), ('auto_detect', 'Auto Detect')], default='auto_detect', help_text='How to parse paragraphs from content', max_length=20),
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chapter_image_upload_to')),
                ('caption', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(help_text='Order in chapter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.chapter')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
