# Generated by Django 5.2.2 on 2025-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
