# Generated by Django 5.2.2 on 2025-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='content_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of content at this version for reconstruction', null=True),
        ),
    ]
