# Generated by Django 5.2.2 on 2025-06-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="target_languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Languages to translate this book into",
                related_name="target_books",
                to="languages.language",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="original_language",
            field=models.ForeignKey(
                help_text="Original language of the book",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="languages.language",
            ),
        ),
    ]
