# Generated by Django 5.2.2 on 2025-06-30 16:53

import books.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="version",
            field=books.fields.AutoIncrementingPositiveIntegerField(
                blank=True, null=True
            ),
        ),
    ]
