# Generated by Django 5.2.2 on 2025-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="key_terms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Important terms for consistent translation",
            ),
        ),
    ]
