# Generated by Django 5.2.2 on 2025-07-06 18:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_chapter_content_file_path_chapter_paragraph_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='image', help_text='Type of media content', max_length=20)),
                ('file', models.FileField(upload_to='chapter_media_upload_to', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'bmp', 'mp3', 'wav', 'ogg', 'm4a', 'flac', 'aac', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv', 'pdf', 'doc', 'docx', 'txt', 'rtf', 'odt'])])),
                ('title', models.CharField(blank=True, help_text='Title or name of the media', max_length=255)),
                ('caption', models.TextField(blank=True, help_text='Description or caption')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility text', max_length=255)),
                ('position', models.PositiveIntegerField(help_text='Order in chapter')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds (for audio/video)', null=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether media has been processed')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for video/audio content', null=True, upload_to='chapter_media_thumbnails/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='books.chapter')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['chapter', 'media_type'], name='books_chapt_chapter_6b4a2f_idx'), models.Index(fields=['media_type', 'is_processed'], name='books_chapt_media_t_c80862_idx')],
            },
        ),
    ]
