# Generated by Django 5.2.2 on 2025-06-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_target_languages_alter_book_original_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="target_languages",
        ),
    ]
