# Generated by Django 5.2.2 on 2025-06-27 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_chapter_key_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.CharField(
                blank=True,
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_slug",
                        message='Slug can contain any characters except whitespace and /\\?%*:|"<>',
                        regex='^[^\\s/\\\\?%*:|"<>]+$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="slug",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_slug",
                        message='Slug can contain any characters except whitespace and /\\?%*:|"<>',
                        regex='^[^\\s/\\\\?%*:|"<>]+$',
                    )
                ],
            ),
        ),
    ]
