# Generated by Django 5.2.2 on 2025-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_slug_alter_chapter_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("translating", "Translating"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("private", "Private"),
                    ("error", "Error"),
                ],
                default="draft",
                help_text="Chapter status",
                max_length=20,
            ),
        ),
    ]
